let mapleader=" "

syntax on
filetype indent on

set expandtab
set softtabstop=4
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set number
set relativenumber
set showcmd
set cursorline
set scrolloff=5
set ruler
set hlsearch
set incsearch
set ignorecase
set smartcase
set wrap
set wildmenu

nnoremap s <Nop>
nnoremap S :w<CR>
nnoremap Q :q<CR>
nnoremap R :source $MYVIMRC<CR>

nnoremap <LEADER><CR> :nohlsearch<CR>
nnoremap sj :set splitbelow<CR>:split<CR>
nnoremap sk :set nosplitright<CR>:split<CR>
nnoremap sl :set splitright<CR>:vsplit<CR>
nnoremap sh :set nosplitright<CR>:vsplit<CR>

nnoremap <LEADER>l <C-w>l
nnoremap <LEADER>j <C-w>j
nnoremap <LEADER>k <C-w>k
nnoremap <LEADER>h <C-w>h

nnoremap <up> :res +5<CR>
nnoremap <down> :res -5<CR>
nnoremap <left> :vertical resize-5<CR>
nnoremap <right> :vertical resize+5<CR>

nnoremap <LEADER>q :q<CR>

function! AddComment()
    let line = getline('.')
    call setline('.', '// ' . line)
endfunction

nnoremap <C-/> :call AddComment()<CR>
nnoremap <C-_> :call AddComment()<CR>
